apiVersion: v1
kind: Pod
metadata:  
  name: hello 
  labels: 
    color: green
spec: 
 containers: 
   - name: hellopod 
     image: nginx 
---
apiVersion: v1
kind: Service 
metadata: 
  name: javasvc 
spec: 
 selector: 
   color: green 
 ports: 
   - protocol: TCP 
     port: 80
     targetPort: 80         
