apiVersion: v1
kind: Pod
metadata: 
  name: javapof
  labels: 
    color: green 
spec: 
  containers: 
    - name: nginx
      image: nginx 

---
apiVersion: v1
kind: Service 
metadata: 
   name: svc 
spec: 
  type: NodePort 
  selector:
    color: green 
  ports: 
    - protocol: TCP 
      port: 80
      targetPort: 80                 