apiVersion: v1
kind: Pod
metadata: 
   name: javapython
   labels: 
     color: red  
spec: 
  containers: 
    - name: javakumar 
      image: nginx 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: javahello 
spec: 
  type: LoadBalancer 
  selector: 
    color: red 
  ports: 
    - port: 80 
      targetPort: 80
      protocol: TCP                