apiVersion: v1 
kind: Pod
metadata: 
  name: request
spec: 
  containers: 
     - name: java 
       image: nginx 
       resources: 
         requests: 
            memory: "128Mi"
            cpu: "50m" 
         limits: 
           memory: "256mi"
           cpu: "100m" 
                