apiVersion: v1
kind: Pod
metadata: 
  name: javahello
spec: 
  containers: 
    - name: hello 
      image: nginx 
      resources: 
        requests: 
          memory: "128Mi"
          cpu: "59m"
        limits: 
          memory: "256Mi" 
          cpu: "200m" 
                   