apiVersion: v1
kind: Secret 
metadata: 
  name: hello 
data: 
  username: YWRtaW4= 

---
apiVersion: v1
kind: Pod 
metadata: 
   name: java123 
spec: 
  containers: 
    - name: jav 
      image: nginx 
      env: 
       - name: USERNAME 
         valueFrom: 
           secretKeyRef: 
             name: hello 
             key: username    
