apiVersion: v1
kind: Deployment
metadata: 
  name: java
  labels: 
   color: green  
spec: 
 replicas: 3
 selector: 
  matchLabels: 
   color: green 
 template: 
   metadata: 
   labels: 
    color: green
   spec: 
     containers: 
       - name: java 
         image: nginx 
         
    